# Generated by Django 5.1.6 on 2025-04-07 12:39

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_approval_date_employee_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=employee.models.employee_document_path),
        ),
    ]
