# Generated by Django 5.1.6 on 2025-03-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_employee_data', 'Can view employee data'), ('add_employee_data', 'Can add employee data'), ('change_employee_data', 'Can change employee data'), ('delete_employee_data', 'Can delete employee data'), ('view_contract', 'Can view contract'), ('add_contract', 'Can add contract'), ('change_contract', 'Can change contract'), ('delete_contract', 'Can delete contract'), ('view_attendance', 'Can view attendance'), ('add_attendance', 'Can add attendance'), ('change_attendance', 'Can change attendance'), ('delete_attendance', 'Can delete attendance'), ('view_salary', 'Can view salary'), ('process_payroll', 'Can process payroll'), ('manage_advances', 'Can manage salary advances'), ('view_training', 'Can view training'), ('add_training', 'Can add training'), ('change_training', 'Can change training'), ('delete_training', 'Can delete training'), ('view_evaluation', 'Can view evaluation'), ('add_evaluation', 'Can add evaluation'), ('change_evaluation', 'Can change evaluation'), ('view_leave', 'Can view leave requests'), ('add_leave', 'Can add leave requests'), ('approve_leave', 'Can approve leave requests'), ('view_reward_discipline', 'Can view rewards and disciplines'), ('add_reward_discipline', 'Can add rewards and disciplines'), ('change_reward_discipline', 'Can change rewards and disciplines'), ('view_reports', 'Can view reports'), ('generate_reports', 'Can generate reports'), ('manage_users', 'Can manage user accounts'), ('assign_permissions', 'Can assign permissions'), ('view_activity_history', 'Can view all activity history')]},
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('DATA_ACCESS', 'Data Access'), ('DATA_MODIFICATION', 'Data Modification'), ('REPORT_GENERATION', 'Report Generation'), ('PERMISSION_CHANGE', 'Permission Change'), ('SYSTEM_CONFIGURATION', 'System Configuration'), ('EMAIL_SENT', 'Email Sent'), ('DOCUMENT_DOWNLOAD', 'Document Download')], default='DATA_ACCESS', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_us_user_id_f07708_idx'), models.Index(fields=['activity_type'], name='accounts_us_activit_8a5b92_idx'), models.Index(fields=['timestamp'], name='accounts_us_timesta_7c259d_idx'), models.Index(fields=['module'], name='accounts_us_module_809177_idx')],
            },
        ),
    ]
