# Generated by Django 5.1.6 on 2025-04-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole_alter_permission_access_right_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='RolePermission',
        ),
    ]
