# Generated by Django 5.1.6 on 2025-03-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
                ('category', models.CharField(choices=[('user', 'User Account'), ('leave', 'Leave Management'), ('attendance', 'Attendance'), ('performance', 'Performance'), ('payroll', 'Payroll & Salary'), ('task', 'Task Management'), ('workflow', 'Workflow'), ('system', 'System Notifications')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.TextField(blank=True, help_text='Variables to use in template, comma separated', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('context_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.emailtemplate')),
            ],
        ),
    ]
