# Generated by Django 5.1.6 on 2025-03-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('leave_request', 'Leave Request'), ('expense_claim', 'Expense Claim'), ('asset_request', 'Asset Request'), ('contract', 'Contract'), ('task', 'Task')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_type', models.CharField(choices=[('approval', 'Approval'), ('notification', 'Notification'), ('auto_action', 'Automated Action')], max_length=20)),
                ('approver_type', models.CharField(blank=True, choices=[('specific_user', 'Specific User'), ('manager', 'Line Manager'), ('department_head', 'Department Head'), ('hr', 'HR Personnel'), ('admin', 'Administrator')], max_length=20, null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('skip_condition', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('specific_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowdefinition')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepInstance',
            fields=[
                ('step_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='workflow.workflowinstance')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowstep')),
            ],
            options={
                'ordering': ['workflow_instance', 'workflow_step__order'],
            },
        ),
    ]
