# Generated by Django 5.1.6 on 2025-03-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('onboarding_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Not Started', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('Document', 'Document Submission'), ('Training', 'Training'), ('Meeting', 'Meeting'), ('Account', 'Account Setup'), ('Equipment', 'Equipment Assignment'), ('Policy', 'Policy Acknowledgement'), ('Other', 'Other')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('department_specific', models.BooleanField(default=False)),
                ('position_specific', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(default=7)),
                ('resources', models.TextField(blank=True, null=True)),
                ('responsible_role', models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('IT', 'IT'), ('Employee', 'Employee'), ('Admin', 'Admin')], default='HR', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.position')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTaskStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Not Applicable', 'Not Applicable')], default='Not Started', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.employeeonboarding')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtask')),
            ],
            options={
                'unique_together': {('onboarding', 'task')},
            },
        ),
    ]
